### ISSUE TITLE
make searching work w/ server side

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#137]
# Description

* Filtering now only works on the current page, it should send a new http request to get the results from all podcasts
* search params should be added to the query string in the URL
# Tasks
- [ ] add searching to the API
- [ ] change frontend to send new http request for filtering
- [ ] add filter params to the URL (search query and tags)
